### ISSUE TITLE
Support ID providers that don't support obtaining an API token via WWW-Authenticate challenge

### ISSUE THREAD

**Issue by astefanutti** [astefanutti/kubebox#1]
Documentation for OpenShift can be found at:
- https://docs.openshift.org/latest/architecture/additional_concepts/authentication.html#oauth
- https://docs.openshift.com/container-platform/latest/install_config/configuring_authentication.html#install-config-configuring-authentication

**Comment by SEJeff** [comment]
Definitely a problem on clusters that auth primarily via oidc, like every single CoreOS tectonic cluster, or anything setup using [dex](https://github.com/coreos/dex) for tying into enterprise LDAP auth or any other provider.

**Comment by edevil** [comment]
I suppose this is why I can't login to GKE clusters? They use an auth-provider:

```
- name: gke_...
  user:
    auth-provider:
      config:
        access-token: ...
        cmd-args: config config-helper --format=json
        cmd-path: /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud
        expiry: "2019-07-05T10:46:51Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
