### ISSUE TITLE
CPU limits wrong

### ISSUE THREAD

**Issue by lduparc** [astefanutti/kubebox#103]
Running Kubebox (latest version)

CPU LImit (red line) display CPU request config and not real limit set in Deployment config.
Checking kubernetes dashboard, cpu is  well set. All ok concerning memory.

Eg:
```
resources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    cpu: 1
    memory: 2Gi
```

Screenshot from Kubebox:

![Screenshot 2020-11-11 at 12 37 57](https://user-images.githubusercontent.com/790935/98807317-be933480-241a-11eb-91b9-36b544ab060d.png)

Screenshot from Kubernetes dashboard:

<img width="438" alt="Screenshot 2020-11-11 at 12 39 32" src="https://user-images.githubusercontent.com/790935/98807461-f7330e00-241a-11eb-928e-06358391e7f4.png">
