### ISSUE TITLE
Logs not updated

### ISSUE THREAD

**Issue by lduparc** [astefanutti/kubebox#108]
Using `echo -e "something\r"` logs are not shown
Same using `curl --progress-bar` loga appear once download is done and are not updated

Thanks

**Comment by astefanutti** [comment]
Do you mean you have a container that runs `echo -e "something\r"`? Would you have an example of a Deployment or a Pod so that we can reproduce?

**Comment by lduparc** [comment]
Hi,

Easy to reproduce, I'm on mac os X Catalina with a running KUbernetes based on docker-desktop. 
Deploy a container (java, busybox, bash...others) and set command to do an infinite loop doing `echo -e "something\r"`. 

Or run a curl command like this one `curl --progress-bar "https://....."` nothing shown until the end of curl.

I don't know if this related to kubebox itself. 

Thanks,

**Comment by astefanutti** [comment]
Thanks, I've been able to reproduce with:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
    - image: busybox
      command: ["/bin/sh"]
      args: ["-c", "x=1; while true; do echo -e \"test $((x++))\r\"; sleep 1; done"]
      imagePullPolicy: IfNotPresent
      name: busybox
  restartPolicy: Always
```
