### ISSUE TITLE
Support Digital Ocean Kubernetes

### ISSUE THREAD

**Issue by andycmaj** [astefanutti/kubebox#53]
DO kubernetes config uses an `ExecCredential`.
Any advice on how i could contribute here? 

## kube config
```
users:
- name: do-sfo2-async-do-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kubernetes
      - cluster
      - kubeconfig
      - exec-credential
      - --version=v1beta1
      - --context=default
      - {SOME GUID}
      command: doctl
      env: null
```

## exec

basically the result of the exec here is [TLS client auth certs](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#input-and-output-formats).

```bash
$ doctl kubernetes cluster kubeconfig exec-credential --version=v1beta1 --context=default {THE GUID FROM ABOVE}

{
  "kind": "ExecCredential",
  "apiVersion": "client.authentication.k8s.io/v1beta1",
  "spec": {},
  "status": {
    "expirationTimestamp": "2019-07-28T17:43:57Z",
    "clientCertificateData": "-----BEGIN CERTIFICATE-----\n*****\n-----END CERTIFICATE-----\n",
    "clientKeyData": "-----BEGIN RSA PRIVATE KEY-----\n*****\n-----END RSA PRIVATE KEY-----\n"
  }
}

```
