### ISSUE TITLE
Kubebox should simply work the way kubectl works

### ISSUE THREAD

**Issue by k1-hedayati** [astefanutti/kubebox#6]
Generally Kubebox should simply work the way kubectl works. I've copied binary to kubernetes master node and ran it from there and it's asking me for credentials while kubectl works fluently.
I believe even running `kubectl` under the hood won't hurt.

**Comment by astefanutti** [comment]
This should be addressed by f7d1e09b2d42c1ecabe214f13a2a87ed3f1bfd84.

**Comment by k1-hedayati** [comment]
Seems like f7d1e09 addresses running kubebox inside a pod, not in a host node

**Comment by astefanutti** [comment]
Correct. I need to check how `kubectl` is dealing connection from host node...

**Comment by k1-hedayati** [comment]
And so it would be possible to run kubebox on every machine that has proper `kubectl` configuration

**Comment by astefanutti** [comment]
I guess `kubectl` relies on the `KUBECONFIG` environment variable, which Kubebox should support with #9.

**Comment by astefanutti** [comment]
@k1-hedayati I've just release version `0.2.0` that contains support for the `KUBECONFIG` environment variable. Would you be able to give it a spin?

**Comment by k1-hedayati** [comment]
Sure, this is the result:
```
➜  ~ ./kubebox-linux 
fs.js:663
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open 'local.crt'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at Context.getMasterApi ([eval]:349:21)
    at new Kubebox ([eval]:1145:53)
    at Object.1../lib/kubebox ([eval]:15:1)
    at s ([eval]:1:254)
    at e ([eval]:1:425)
    at [eval]:1:443
    at Script.runInThisContext (vm.js:65:33)
    at Object.runInThisContext (vm.js:199:38)
```
Kubeconfig:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: local.ca
    server: https://X.X.X.X:6443
  name: local
contexts:
- context:
    cluster: local
    user: kube-local
  name: local
current-context: local
kind: Config
preferences: {}
users:
- name: kube-local
  user:
    client-certificate: local.crt
    client-key: local.key
```
