### ISSUE TITLE
ENOENT Error with AWS EKS

### ISSUE THREAD

**Issue by FriedCircuits** [astefanutti/kubebox#60]
I am trying to use kubebox with AWS EKS. I updated to 0.6.0 which supports the exec auth. I have been unsuccessful in connecting due to the following error:

spawn aws-iam-authenticator ENOENT 

Pasting in a token doesn't seem to work either.

Any ideas? What am I missing?

**Comment by astefanutti** [comment]
It seems Kubebox is not able to execute `aws-iam-authenticator`. Could you try running:

    $ which aws-iam-authenticator

Could you provide your kubeconfig details with the auth provider section as well.

**Comment by FriedCircuits** [comment]
MacOS: /usr/local/bin/aws-iam-authenticator

```yaml
contexts:
- context:
    cluster: eks-cluster
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "eks-cluster"
      env:
      - name: "AWS_PROFILE"
        value: "default"
```
