### ISSUE TITLE
Error "Unable to verify first certificate" on connection

### ISSUE THREAD

**Issue by omar-nahhas** [astefanutti/kubebox#7]
I cannot log-in into a cluster if my cluster ca is in the form of certificate-authority-data

(from .kube/config ...)
```
- cluster:
    certificate-authority-data: asdfasdfasdfasdfasfdasdfasdfasdf
```

**Comment by astefanutti** [comment]
I've just tried connecting with a user `token` and cluster `certificate-authority-data` configured, but haven't been able to reproduce.

It should be supported:
https://github.com/astefanutti/kubebox/blob/68fd5335626fb3b643da032cd8de7877e8750970/lib/config/context.js#L67-L69

Could you confirm that the `certificate-authority-data` field is base64 encoded. Besides, could you provide more information on your environment so that we can try reproducing?

**Comment by loffelmacher** [comment]
Getting the same error message here. Using a username/password in the login box, I am able to connect to the cluster using kubectl. I provided an URL to an AWS ELB for the URL in login box, same one I found in my kube config.

**Comment by astefanutti** [comment]
It seems the "Unable to verify first certificate" is returned when some intermediate certificates aren't bundled along with the server certificate. It may actually work with `kubectl` because it's more permissive than Node.

**Comment by astefanutti** [comment]
@loffelmacher Would you be able to share more info about your kube config content and the server certificate that may help identifying the root cause?

**Comment by sabrehagen** [comment]
I'm experiencing the same issue. Here's my `kubeconfig`:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDe...redacted...=
    server: https://104.xxx.xxx.xxx
  name: staging
contexts:
- context:
    cluster: staging
    user: staging
  name: staging
kind: Config
preferences: {}
users:
- name: staging
  user:
    auth-provider:
      config:
        access-token: ya29.redacted
        expiry: 2018-10-21T12:10:30.613021286Z
      name: gcp
```

**Comment by johnpoth** [comment]
@infinitydon the '_insecure-skip-tls-verify_' flag is [taken](https://github.com/astefanutti/kubebox/blob/master/lib/config/cluster.js#L18) into account in kubebox (I use it all the time when running clusters locally). Are you experiencing the issue in the browser or when using node?

**Comment by infinitydon** [comment]
@johnpoth -- I am facing this problem any time I initiate kubebox from my bash shell. And that is the format of the kubeconfig I am using, I can communicate with the cluster using kubectl without any issues.

Is there some way to capture some log or debug?

**Comment by astefanutti** [comment]
One possible cause could be the difference between root CA sourced from Node compared to Golang.

Golang sources from: https://golang.org/src/crypto/x509/root_linux.go
While Node sources from: https://github.com/nodejs/node/blob/v11.x/src/node_root_certs.h

The `NODE_EXTRA_CA_CERTS` environment variable is used by Node as a way to add extra CA certificates, as documented in https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file. It must be a file containing certificates in PEM format.

From the Node documentation, neither the well known nor extra certificates are used when the `ca` options property is explicitly specified for a TLS or HTTPS client, which is what Kubebox is doing when the `certificate-authority-data` field is present in the _kubeconfig_ file. So that may explain why the error occurs when `certificate-authority-data` is present. 

It'd be awesome if someone facing the issue could try setting the `NODE_EXTRA_CA_CERTS`, with a file containing certificates from https://golang.org/src/crypto/x509/root_linux.go.

For the error occurring with `certificate-authority-data` present in _kubeconfig_ file, it may be that intermediate certificates have to be bundled in the field, e.g.:

```
$ cat \
 cert.pem \
 intermediate-cert.pem \
 ...
 > fullchain.pem
```

If someone facing the issue for that case could be doing the test, that'd be awesome as well.

Otherwise, it'd be great if someone facing the issue could confirm the above, by providing the server certificate full chain, and the non-redacted `certificate-authority-data` value if present.

**Comment by cscetbon** [comment]
@astefanutti I created a file with all my certificates in it and used `NODE_EXTRA_CA_CERTS` to reference that file. Not much luck ...
```
cat ~/.kube/creds/dev2/*.pem > ~/Downloads/ca-files.pem
NODE_EXTRA_CA_CERTS=~/Downloads/ca-files.pem kubebox
```

**Comment by cscetbon** [comment]
>Could you provide your kubeconfig file relevant info?

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: creds/dev2/ca.pem
    server: https://master.dev2.test.xx.com
  name: dev2
- context:
    cluster: dev2
    namespace: my_ns
    user: dev2-cscetbon
  name: dev2
- name: dev2-cscetbon
  user:
    client-certificate: creds/dev2/cscetbon.pem
    client-key: creds/dev2/cscetbon-key.pem
```

> Could you provide more info about your server certificate, i.e., its certificate full chain?

I don't have this information
> What Kubernetes setup do you use?

wdym ? 1.9.4 nodes running coreOS

> If you're using certificate-authority or certificate-authority-data in your kubeconfig file, could you add the intermediate certificates if any, with the least authoritative certificate first - your server's certificate, followed by the furthest missing intermediate, and then the next closest to the root, etc (without the root one).

As you can see I user `certificate-authority` but I don't have access to any intermediate certificates and don't know if there are
