### ISSUE TITLE
Pending pod crashes v0.7.0: Cannot read property 'concat' of undefined

### ISSUE THREAD

**Issue by drigz** [astefanutti/kubebox#76]
I got the following crash after selecting a Pending pod and hitting enter:

```
TypeError: Cannot read property 'concat' of undefined
    at Object.module.exports.containerStatus (/bin/__nexe_stdin.js:2031:49)
    at Object.module.exports.isContainerWaitingWithReasons (/bin/__nexe_stdin.js:2080:33)
    at ListTable.Dashboard.pods_table.on (/usr/local/google/home/rodrigoq/bin/__nexe_stdin.js:4562:15)
    at ListTable.EventEmitter._emit (/bin/__nexe_stdin.js:7376:20)
    at ListTable.EventEmitter.emit (/bin/__nexe_stdin.js:7399:12)
    at ListTable.List.enterSelected (/bin/__nexe_stdin.js:20988:8)
    at ListTable.<anonymous> (/__nexe_stdin.js:20521:14)
    at ListTable.EventEmitter._emit (/bin/__nexe_stdin.js:7376:20)
    at ListTable.EventEmitter.emit (/bin/__nexe_stdin.js:7399:12)
    at Program.<anonymous> (/bin/__nexe_stdin.js:24075:15)
```

The container status is:

```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-01-20T09:54:34Z"
    message: '0/1 nodes are available: 1 Insufficient codemeter.wibu.com/codemeter.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: BestEffort
```
