### ISSUE TITLE
Refresh oidc tokens

### ISSUE THREAD

**Issue by lucidyan** [astefanutti/kubebox#84]
When using [oidc authentification](
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#option-1-oidc-authenticator), kubebox don't get refresh tokens automatically. So we got every time:
```
Failed to get resource /auth/realms/master/protocol/openid-connect/token, status code: 400
```
![image](https://user-images.githubusercontent.com/5789108/76438714-69ef7380-63cc-11ea-9c64-db3e9f7e1a4e.png)

But if we run any command with kubectl, it refresh token and kubebox will work before token refresh again.

**Comment by johnpoth** [comment]
Hi @lucidyan, refreshing oidc tokens automatically should be supported. Could you share the relevant part of your kubernetes config ? Thanks !

**Comment by lucidyan** [comment]
Hi, @johnpoth ! 

I have the Keycloak 8.0.1 [configured to refresh tokens](https://www.keycloak.org/docs/8.0/authorization_services/) with some period. It controlled by [Access Token Lifespan](https://github.com/keycloak/keycloak-documentation/blob/master/server_admin/topics/sessions/timeouts.adoc) parameter.

K8S part of user config:
```
- name: USER_NAME
  user:
    auth-provider:
      config:
        client-id: kubernetes
        client-secret: CLIENT_SECRET
        id-token: ID_TOKEN
        idp-issuer-url: https://{KEYCLOAK_SERVER_URL}/auth/realms/master
        refresh-token: REFRESH-TOKEN
      name: oidc
```
