### ISSUE TITLE
would like to configure the namespace cadvisor runs in

### ISSUE THREAD

**Issue by brennantaylor** [astefanutti/kubebox#88]
Right now it is hardcoded to `cadvisor`. It would be nice to be able to configure this.

**Comment by astefanutti** [comment]
Thanks a lot for the suggestion. That makes totally sense.

I see a couple of options:
* Pass the namespace as a CLI option. Having a proper CLI is something we plan provide (e.g. for #77). However, I was more thinking of it as an emulation of `kubectl` CLI, rather than to configure Kubebox itself. Besides, the cAdvisor namespace is a rather static information, per cluster, so you may not want to pass it each time, but rather define it once. That leads to the next option;
* Have a _dot_ configuration file for Kubebox.

Ideally, it should work also for the Web version. CLI can be emulated with arguments passed in the URL. A _dot_ file could be emulated with a config map. Maybe even for the non-Web version, a config map could old the configuration and be looked up, but that's probably better to stick to the _dot_ file convention.

WDYT?

**Comment by brennantaylor** [comment]
Yeah I've also struggled defining an isomorphic config that feels right in both the cli and web.

It's pretty standard to inject env vars or mount entire files into a container with configmaps. Env vars also let you use `env` or `envFrom` in podSpecs to define it. Changing the cli args is trivial too.

Env vars could be made to work ok in the browser with query params like you mentioned:

```
# using dotenv somewhere in index.js: require('dotenv').config()
echo "CADVISOR_NAMESPACE=default" > .env
npm index.js
```

```
# just on the command line
env "CADVISOR_NAMESPACE=default" npm index.js
```

```
# in the browser parse the query params as env vars?
http://kubebox.mydomain.com/?CADVISOR_NAMESPACE=default
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubebox
spec:
  selector:
    matchLabels:
      name: kubebox
  template:
    metadata:
      name: kubebox
    spec:
      serviceAccountName: kubebox
      containers:
      - image: astefanutti/kubebox:server
        name: kubebox
        env:
        - name: CADVISOR_NAMESPACE # EZ in k8s too
           value: default
        ports:
        - containerPort: 8080
          protocol: TCP
```
